const fs = require("fs");
const path = require("path");
const solc = require("solc");

const contractPath = path.join(__dirname, "..", "src", "ERC721Mintable.sol");
const source = fs.readFileSync(contractPath, "utf8");

const input = {
  language: "Solidity",
  sources: {
    "contracts/ERC721Mintable.sol": { content: source },
  },
  settings: {
    optimizer: { enabled: false, runs: 200 },
    evmVersion: "prague",
    outputSelection: {
      "*": {
        "*": ["abi", "evm.bytecode.object"],
      },
    },
  },
};

function resolveImport(importPath) {
  try {
    if (importPath.startsWith("@openzeppelin/")) {
      const resolvedPath = path.join(
        __dirname,
        "..",
        "node_modules",
        importPath
      );
      return { contents: fs.readFileSync(resolvedPath, "utf8") };
    }

    const localPath = path.join(path.dirname(contractPath), importPath);
    return { contents: fs.readFileSync(localPath, "utf8") };
  } catch (error) {
    return { error: `File not found: ${importPath}` };
  }
}

const output = JSON.parse(
  solc.compile(JSON.stringify(input), { import: resolveImport })
);

if (output.errors && output.errors.length > 0) {
  output.errors.forEach((error) => console.error(error.formattedMessage));
  const fatalErrors = output.errors.filter(
    (error) => error.severity === "error"
  );
  if (fatalErrors.length > 0) {
    process.exit(1);
  }
}

const contract =
  output.contracts["contracts/ERC721Mintable.sol"]["ERC721Mintable"];
const abi = contract.abi;
const bytecode = contract.evm.bytecode.object;

if (!bytecode) {
  console.error("Missing bytecode in compilation output.");
  process.exit(1);
}

const outDir = path.join(__dirname, "..", "public");
const outPath = path.join(outDir, "contract.js");

const fileContents = `// Auto-generated by scripts/compile.js
export const ABI = ${JSON.stringify(abi, null, 2)};
export const BYTECODE = "0x${bytecode}";
`;

fs.writeFileSync(outPath, fileContents, "utf8");
console.log(`Wrote ${outPath}`);
